/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PodcastsPodcastIdRouteImport } from './routes/podcasts/$podcastId'
import { Route as EpisodesEpisodeIdRouteImport } from './routes/episodes/$episodeId'
import { Route as ApiAudioEpisodeIdRouteImport } from './routes/api/audio.$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsPodcastIdRoute = PodcastsPodcastIdRouteImport.update({
  id: '/podcasts/$podcastId',
  path: '/podcasts/$podcastId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesEpisodeIdRoute = EpisodesEpisodeIdRouteImport.update({
  id: '/episodes/$episodeId',
  path: '/episodes/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioEpisodeIdRoute = ApiAudioEpisodeIdRouteImport.update({
  id: '/api/audio/$episodeId',
  path: '/api/audio/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/audio/$episodeId': typeof ApiAudioEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/audio/$episodeId': typeof ApiAudioEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/audio/$episodeId': typeof ApiAudioEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/episodes/$episodeId'
    | '/podcasts/$podcastId'
    | '/admin/'
    | '/api/audio/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/episodes/$episodeId'
    | '/podcasts/$podcastId'
    | '/admin'
    | '/api/audio/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/episodes/$episodeId'
    | '/podcasts/$podcastId'
    | '/admin/'
    | '/api/audio/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpisodesEpisodeIdRoute: typeof EpisodesEpisodeIdRoute
  PodcastsPodcastIdRoute: typeof PodcastsPodcastIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAudioEpisodeIdRoute: typeof ApiAudioEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$podcastId': {
      id: '/podcasts/$podcastId'
      path: '/podcasts/$podcastId'
      fullPath: '/podcasts/$podcastId'
      preLoaderRoute: typeof PodcastsPodcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$episodeId': {
      id: '/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof EpisodesEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/$episodeId': {
      id: '/api/audio/$episodeId'
      path: '/api/audio/$episodeId'
      fullPath: '/api/audio/$episodeId'
      preLoaderRoute: typeof ApiAudioEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpisodesEpisodeIdRoute: EpisodesEpisodeIdRoute,
  PodcastsPodcastIdRoute: PodcastsPodcastIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAudioEpisodeIdRoute: ApiAudioEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
